#!/usr/bin/bash

if [ -n "$1" ]; then
  case $1 in
      -r|--disable-dry-run)
          read -rp "ВНИМАНИЕ!!! Ты запустил продакшн сборку. Ты понимаешь риск и хочешь продолжить?[Y|y] " answer
          case $answer in
              [yY] ) nohup python3.11 app/init.py --prod -r &;;
              * ) exit 0;;
          esac
          ;;
      -*|--*)
          echo "Неизвестная опция $1"
          exit 1
          ;;
  esac
else
  echo "Это DRY RUN mode, для выключения DRY RUN используй опцию -r"
  nohup python3.11 app/init.py --prod &
fi
pgrep -l init.py